#!/bin/bash

trap exit SIGINT
shopt -s huponexit

for image in "$@"
do
	sxiv "$image" &
	echo "$image"
	echo -n 'Palette: '
	./vibrant.py "$image" | hex2col
	#echo -n 'All:     '
	#./vibrant.py -a "$image" | hex2col
        xdotool key q
	echo
done
